# Generated by Django 4.1.3 on 2022-11-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=1024)),
                ('member_number', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=1024)),
                ('member_age', models.IntegerField()),
                ('member_city', models.CharField(max_length=1024)),
                ('member_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Member_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=1024)),
                ('enter_counts', models.IntegerField()),
                ('enter_total', models.IntegerField()),
                ('missions_total', models.IntegerField()),
                ('missions_counts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('mission_check', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('is_published', models.BooleanField()),
                ('post_type', models.CharField(choices=[('Article', 'Article'), ('Story', 'Story')], default='Article', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.CharField(max_length=1024)),
                ('specialist_Specialization', models.CharField(max_length=1024)),
                ('specialist_city', models.CharField(max_length=512)),
                ('specialist_phone', models.IntegerField()),
                ('specialist_specialization_image', models.ImageField(upload_to='images/')),
                ('specialist_image', models.ImageField(upload_to='images/')),
                ('specialist_personal_page', models.URLField()),
                ('specialist_rate', models.FloatField()),
                ('specialist_confirmation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.post')),
            ],
        ),
    ]
