# Generated by Django 4.1.3 on 2022-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Member_group',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.AddField(
            model_name='group',
            name='complete_mission',
            field=models.IntegerField(default=0),
        ),
    ]
