# Generated by Django 4.1.3 on 2022-11-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Website', '0002_delete_member_delete_member_group_delete_specialist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='accounts.member'),
        ),
        migrations.AddField(
            model_name='group',
            name='missions_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='specialist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.specialist'),
        ),
        migrations.AddField(
            model_name='mission',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Website.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='member_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
