# Generated by Django 4.1.3 on 2022-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_group_member_group_missions_total_group_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
