# Generated by Django 4.1.3 on 2022-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_mission_member_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chat_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_check',
            field=models.BooleanField(default=0),
        ),
    ]
