# Generated by Django 4.1.3 on 2022-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_group_chat_url_alter_mission_mission_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chat_url',
            field=models.URLField(default=''),
        ),
    ]
