# Generated by Django 4.1.3 on 2022-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialist_specialist_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='type',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
