# Generated by Django 4.1.3 on 2022-11-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_member_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='type',
            field=models.CharField(default='specialist', max_length=512),
        ),
    ]
